import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, writeFile, rm, mkdir, readFile, access } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { LoadType, type Track } from "shoukaku";
import { YoutubeResolver, runYoutube, youtubeMetadata, resetYoutubeDecoderCache, validateYoutubeMediaUrl, youtubeVideoId } from "../src/audio/youtube.js";

const id = "2I3PLVuKNtw";
const uri = `https://www.youtube.com/watch?v=${id}`;
const media = `https://rr1.googlevideo.com/videoplayback?expire=${Math.floor(Date.now() / 1000) + 3600}&sig=PRIVATE`;
const options = { binary: "/fixture/yt-dlp", cookies: "/fixture/private-cookies" };
const extracted = { id, title: "Sastanàqqàm", channel: "ANTI- Records", duration: 205, url: media };
const httpTrack: Track = { encoded: "private-transport", pluginInfo: {}, info: { identifier: media, uri: media, title: "transport", author: "unknown", length: 204601, position: 0, sourceName: "http", isSeekable: true, isStream: false } };
const load = async () => ({ loadType: LoadType.TRACK as const, data: httpTrack });
test("YouTube labels remixer credits that are missing from a catalog title", () => {
  const remix = youtubeMetadata({ id: "KIhaSBYVRNM", title: "Bitch Better Have My Money", channel: "Rihanna", channel_is_verified: true, duration: 264, description: "Provided to YouTube by Universal Music Group\nRemixer, Studio Personnel: Michael Woods\nAuto-generated by YouTube." });
  assert.equal(remix.info.title, "Bitch Better Have My Money (Michael Woods remix)");
  const original = youtubeMetadata({ ...extracted, description: "Studio Personnel, Mixer: Manny Marroquin" });
  assert.equal(original.info.title, extracted.title);
});
test("artist metadata does not hide the actual uploading channel", () => {
  const item = youtubeMetadata({ ...extracted, artist: "Rihanna", channel: "BEAST COAST" });
  assert.equal(item.info.author, "BEAST COAST");
});

test("authenticated YouTube keeps exact recording identity while using a private transport", async () => {
  const resolver = new YoutubeResolver(options, async (_config, args) => {
    assert.equal(args.at(-1), uri); assert.ok(args.includes("--skip-download")); assert.ok(args.includes("--check-formats")); return extracted;
  });
  const result = await resolver.resolve(uri, load);
  assert.equal(result.loadType, LoadType.TRACK);
  if (result.loadType !== LoadType.TRACK) return;
  assert.equal(result.data.encoded, "private-transport");
  assert.equal(result.data.info.uri, uri); assert.equal(result.data.info.sourceName, "youtube");
  assert.equal(result.data.info.identifier, id); assert.equal(result.data.info.length, 204601);
  assert.ok(!JSON.stringify(result.data.info).includes("PRIVATE"));
});
test("authenticated resolver rejects a different upload before contacting the audio service", async () => {
  const resolver = new YoutubeResolver(options, async () => ({ ...extracted, id: "85CLbxM8gQ8" }));
  await assert.rejects(resolver.resolve(uri, async () => { assert.fail("must not load wrong upload"); }), /different upload/);
});
test("media allowlist rejects internal, disguised, unencrypted and expired addresses", () => {
  for (const bad of ["http://rr1.googlevideo.com/videoplayback", "https://127.0.0.1/videoplayback", "https://googlevideo.com.attacker.test/videoplayback", media.replace("rr1.googlevideo.com", "rr1.googlevideo.com:8443"), media.replace("https://", "https://user:pass@"), media.replace(/expire=\d+/, "expire=1"), media + "#fragment"]) {
    assert.throws(() => validateYoutubeMediaUrl(bad), /unsafe|expired/);
  }
  assert.equal(validateYoutubeMediaUrl(media), media);
});
test("YouTube URL parsing never turns arbitrary URLs or playlist URLs into subprocess input", () => {
  assert.equal(youtubeVideoId(uri), id); assert.equal(youtubeVideoId(`https://youtu.be/${id}`), id);
  for (const bad of ["https://youtube.com.attacker.test/watch?v=" + id, "https://www.youtube.com/playlist?list=abc", "https://user@www.youtube.com/watch?v=" + id, "ytsearch:hello", "file:///etc/passwd"]) assert.equal(youtubeVideoId(bad), undefined);
});
test("resolver refuses previews and requests a fresh stream for every retry", async () => {
  let resolutions = 0;
  const resolver = new YoutubeResolver(options, async () => { resolutions++; return extracted; });
  await assert.rejects(resolver.resolve(uri, async () => ({ loadType: LoadType.TRACK, data: { ...httpTrack, info: { ...httpTrack.info, length: 30000 } } })), /incomplete/);
  await resolver.resolve(uri, load); assert.equal(resolutions, 2);
});
test("authenticated search bounds candidates and excludes live, private and incomplete results", async () => {
  const resolver = new YoutubeResolver(options, async (_config, args) => {
    assert.equal(args.at(-1), "ytsearch10:Tinariwen"); assert.ok(args.includes("--flat-playlist"));
    return { entries: [extracted, { ...extracted, is_live: true }, { id }, null] };
  });
  const result = await resolver.search("Tinariwen");
  assert.equal(result.loadType, LoadType.SEARCH);
  if (result.loadType === LoadType.SEARCH) { assert.equal(result.data.length, 1); assert.equal(result.data[0].info.uri, uri); }
});
test("queued extraction cancellation cannot contact the source or start audio", async () => {
  let finish!: (value: unknown) => void; let calls = 0;
  const resolver = new YoutubeResolver(options, async () => { calls++; return new Promise(resolve => { finish = resolve; }); });
  const first = resolver.resolve(uri, load); await Promise.resolve(); await Promise.resolve();
  const abort = new AbortController(); const second = resolver.resolve(uri, load, abort.signal); abort.abort();
  finish(extracted); await first; await assert.rejects(second, /abort/i); assert.equal(calls, 1);
});
test("extractor errors expose neither subprocess output nor inherited bot credentials", async () => {
  const directory = await mkdtemp(join(tmpdir(), "audiobot-youtube-test-"));
  try {
    const cookies = join(directory, "cookies.txt"), binary = join(directory, "extractor");
    await writeFile(cookies, "# Netscape HTTP Cookie File\n", { mode: 0o600 });
    await writeFile(binary, '#!/bin/sh\n[ -z "${DISCORD_TOKEN:-}" ] || exit 9\nprintf "%s\\n" "Sign in required SECRET_COOKIE https://rr1.googlevideo.com/?sig=SECRET_URL" >&2\nexit 1\n', { mode: 0o700 });
    await assert.rejects(runYoutube({ binary, cookies }, []), error => {
      assert.match(String(error), /session expired/); assert.doesNotMatch(String(error), /SECRET|rr1|sig=/); return true;
    });
  } finally { await rm(directory, { recursive: true, force: true }); }
});
test("decoder repair preserves the dedicated account session and unrelated state", async () => {
  const directory = await mkdtemp(join(tmpdir(), "audiobot-cache-repair-"));
  try {
    const cookies = join(directory, "cookies.txt"), compiled = join(directory, "youtube-embedded-cache", "youtube-sigfuncs");
    await mkdir(compiled, { recursive: true });
    await writeFile(cookies, "session-fixture", { mode: 0o600 });
    await writeFile(join(compiled, "obsolete.json"), "{}");
    await writeFile(join(directory, "queue-fixture"), "preserve");
    await resetYoutubeDecoderCache({ binary: "/unused", cookies });
    assert.equal(await readFile(cookies, "utf8"), "session-fixture");
    assert.equal(await readFile(join(directory, "queue-fixture"), "utf8"), "preserve");
    await assert.rejects(access(compiled));
  } finally { await rm(directory, { recursive: true, force: true }); }
});

test('playback takes priority over queued metadata while cookie writes remain serialized', async () => {
  let release!: () => void; let active = 0, maxActive = 0; const calls: string[] = [];
  const resolver = new YoutubeResolver(options, async (_options, args) => {
    active++; maxActive = Math.max(maxActive, active);
    const kind = args.includes('--check-formats') ? 'playback' : args.at(-1)!; calls.push(kind);
    try { if (calls.length === 1) await new Promise<void>(resolve => { release = resolve; }); return extracted; }
    finally { active--; }
  });
  const first = resolver.inspect(id); const waiting = resolver.inspect('85CLbxM8gQ8').catch(() => {});
  const playback = resolver.resolve(uri, load); release();
  await Promise.all([first, waiting, playback]); assert.equal(calls[1], 'playback'); assert.equal(maxActive, 1);
});
